version: '2'

services:
  app:
    build:
      context: docker
      dockerfile: app/app.dockerfile
    working_dir: /var/www/html
    volumes:
      - ./laravel:/var/www/html:cached
      - ~/.composer/cache:/var/www/.composer/cache/:delegated
    ports:
      - 80:80
      - 5000:5000
    environment:
      PHP_IDE_CONFIG: "serverName=docker"

  db:
    image: mysql:5.7
    volumes:
      # Use named volume for db data, so that it can persist. 
      # (Clear with `docker-compose down -v`)
      - dbdata:/var/lib/mysql:delegated
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=laravel_docker_root
      - MYSQL_DATABASE=laravel
      - MYSQL_USER=laravel
      - MYSQL_PASSWORD=laravel

  mailhog:
    ## Mailhog image, in order to test mails within the application.
    # (http://localhost:8025/)
    image: mailhog/mailhog
    user: root
    ports:
      - 1025:1025
      - 8025:8025

volumes:
  dbdata:
